[editor]
camera_fov = 60.0
camera_speed = 50.0
camera_start_position_x = 0.0
camera_start_position_y = 0.0
camera_start_position_z = 400.0

[general]
framerate_limit = 60
mouse_sensitivity = 0.05
unit_scale = 1.0
thread_count = 6 # Number of threads to perform multithreaded tasks on

[physics]
ticks_per_second = 60 # Number of times physics engines ticks per second
sub_steps = 4
gravity_x = 0.0
gravity_y = 0.0
gravity_z = 0.0
box2d_enable = true
jolt_enable = false

[rendering]
screen_width = 1920 # Width of screen to display to
screen_height = 1080 # Height of screen to display to
render_width = 1920 # Width of render target (scales up to screen width)
render_height = 1080 # Height of render target (scale up to screen height)
fullscreen = false
borderless = false
shadows_enable = true
physics_interpolation_enable = true
